### ISSUE TITLE
i can not run with ajax.

### ISSUE THREAD

**Issue by bunalng** [aleho/bootstrap-multimodal#1]
do u try with ajax?

**Comment by aleho** [comment]
This plugin has got nothing to do with AJAX. You're probably trying the wrong thing.

**Comment by mbunal** [comment]
please, can you check this: http://adanaonline.com/3/

**Comment by aleho** [comment]
If you've got a specific problem with this project to report, please include a minimal reproducible example at an online service, e.g. JSFiddle.

Sorry, I can't provide support for Bootstrap or common webdev deleted problems.
